version: "3.8"

services:
  forCook:
    build: .
    image: forcook:0.0.0.1
    container_name: forCook
    hostname: forCook
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-forcook:5432/forCook
    ports:
      - "8082:8080"
    depends_on:
      - db-forcook
    networks:
      - banknetwork
  db-forcook:
    image: postgres:14
    restart: always
    hostname: forcook-db
    environment:
      POSTGRES_DB: forCook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - forcook-db:/var/lib/postgres/data/
    ports:
      - "4432:5432"
    networks:
      - banknetwork

volumes:
  forcook-db:

networks:
  banknetwork:
      external: true